// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB4uQiqI7h0xXDKBTD4-4lvIw2WgI9sQk',
    appId: '1:1015297666389:web:c7e6a3f8b887dd9256d3dc',
    messagingSenderId: '1015297666389',
    projectId: 'gymvibedavao',
    authDomain: 'gymvibedavao.firebaseapp.com',
    storageBucket: 'gymvibedavao.firebasestorage.app',
    measurementId: 'G-2L6B2T22Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ViWLJF3e-IJYGvUbMsa9M4rioYNklL0',
    appId: '1:1015297666389:android:0dacac5d973c987256d3dc',
    messagingSenderId: '1015297666389',
    projectId: 'gymvibedavao',
    storageBucket: 'gymvibedavao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlQQV1KsLEL8d7J1DUtDewbUPcS4QdS20',
    appId: '1:1015297666389:ios:0483f76e07ad898156d3dc',
    messagingSenderId: '1015297666389',
    projectId: 'gymvibedavao',
    storageBucket: 'gymvibedavao.firebasestorage.app',
    iosBundleId: 'com.example.gymvibe',
  );
}
